version: "3.7"

services:
  redis:
    image: redis
    #    volumes:
    #  - "./default.conf:/etc/nginx/conf.d/default.conf"
    #  - "./html:/usr/share/nginx/html"
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    driver: bridge
    name: tasks-net
    ipam:
      driver: default
      config:
        - subnet:  10.103.0.1/16