httpApi:
  addr: "0.0.0.0:80"
  base: "/answer"

task:
  addr: "0.0.0.0:31337"
  clients: 4
  letterPath: "./letter"
  localPostboxPath: "./postbox"
  remotePostboxPath: "/root/a-quest/deploy/task3/postbox"

redis:
  addr: "redis:6379"
  scoreKey: "pingpong-scores"
  winnersKey: "pingpong-winners"